# https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - stylecheck
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
