version: "2"

run:
  build-tags:
    - integration

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  exclusions:
    rules:
      # Exclude defer statements from errcheck checks.
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - funlen
          - goconst

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
