version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    gosec:
      excludes:
        - G701
        - G704
        - G706
    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
  exclusions:
    rules:
      - source: "^\\s*defer\\s+"
        linters:
          - errcheck
      - path: _test\.go
        linters:
          - errchkjson
          - gocognit
          - goconst
          - godoclint
          - gosec

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
