version: "2"

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - staticcheck

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
