builds:
  - main: ./cmd/deadnews-template-go/

release:
  prerelease: auto
  footer: |
    See [the CHANGELOG]({{ .GitURL }}/blob/main/CHANGELOG.md) for more details.

changelog:
  sort: asc

nfpms:
  - id: "{{ .ProjectName }}"
    description: Go Project Template
    homepage: "{{ .GitURL }}"
    maintainer: DeadNews <deadnewsgit@gmail.com>
    formats:
      - deb
    bindir: /usr/bin
