builds:
  - main: ./cmd/deadnews-template-go/

release:
  prerelease: auto
  footer: |
    See [the CHANGELOG]({{ .GitURL }}/blob/main/CHANGELOG.md) for more details.

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - ^chore
      - ^test"
      - ^(ci|build|chore)\(deps.*\)
  groups:
    - title: Dependencies
      regexp: ^fix\(deps.*\)
      order: 300
    - title: Features
      regexp: ^feat
      order: 100
    - title: Security
      regexp: ^sec
      order: 150
    - title: Bug fixes
      regexp: ^(fix|refactor)
      order: 200
    - title: Documentation
      regexp: ^docs
      order: 400
    - title: Build process
      regexp: ^(build|ci)
      order: 500
    - title: Other work
      order: 999

nfpms:
  - id: "{{ .ProjectName }}"
    description: Go Project Template
    homepage: "{{ .GitURL }}"
    maintainer: DeadNews <deadnewsgit@gmail.com>
    formats:
      - deb
    bindir: /usr/bin
