services:
  template-go:
    build: .
    healthcheck:
      test: [CMD, /bin/template-go, --healthcheck, http://127.0.0.1:8000/health]
      interval: 1m
      retries: 3
      timeout: 10s
      start_period: 1m
    ports:
      - 127.0.0.1:8000:8000/tcp
